### ISSUE TITLE
Change the Syncano Client Lib main path in package.json

### ISSUE THREAD

**Issue by adamwardecki** [Syncano/syncano-node#130]
Currently, the package.json file points to the `lib/index.js` which when used with unpkg loads a non transpiled and unminified version that can't really be used in the browser.

Scope of the task:
- change `lib/index.js` to `dist/syncano-client.min.js` in `package.json` of @syncano/client

**Comment by mkucharz** [comment]
@adamwardecki can you elaborate a little bit? How exactly you are using library from unpkg? As far as I see unpkg is redirecting by default to `lib/index.js` when you will type:

`https://unpkg.com/@syncano/client -> https://unpkg.com/@syncano/client@0.8.0/lib/index.js`

and browser version is here:

`https://unpkg.com/@syncano/client@0.8.0/dist/syncano-client.min.js`

But I don't think that suggested by you change is solving the problem.. at least it will probably mess with importing library in node env. Any examples of other libs which have it right?

**Comment by adamwardecki** [comment]
Exactly. The redirection that unpkg is doing is not what we want, since `index.js` file is not transpiled and not suitable for browser env. Ideally, doing: `https://unpkg.com/@syncano/client` should point to the minified version, since this what a user would want to have loaded.

Not sure that pointing to the minified and transpiled version will mess the imports in node. Anyhow, I'll do the research and post the findings here.

**Comment by mkucharz** [comment]
This is how docsify is importing libs from unpkg:
`<script src="//unpkg.com/docsify/lib/docsify.min.js"></script>`

**Comment by adamwardecki** [comment]
Yes, but it would be nicer if doing `<script src="https://unpkg.com/@syncano/client"></script>`
would get the latest minified version.

Looked around a bit. We could add "unpkg" field to the package.json which would point to the minified distribution:
`"unpkg": "dist/syncano-client.min.js"`

I.e. [d3](https://github.com/d3/d3/blob/master/package.json) does it like this, so we wouldn't be in a bad company ;)
