### ISSUE TITLE
Sync files without deleting those only on server side (append only)

### ISSUE THREAD

**Issue by mkucharz** [Syncano/syncano-node#147]

**Comment by Idered** [comment]
Maybe like this: `s hosting sync web --merge`

**Comment by mkucharz** [comment]
Merge suggest making copy from the server. I'm thinking about `--no-delete`.

**Comment by Idered** [comment]
`sync` also suggest making copy from the server - it's name suggest two way data flow.  IMHO `--no-delete` ain't good.

`--no-delete` - submit my files to hosting but don't delete old files. What about overwriting files? This name doesn't tell if those will be overwritten or not.

`--merge` - It says clearly that everything will be overwritten but not deleted. It's like js concat method

**Comment by mkucharz** [comment]
`Sync` is about syncing local folder with remote side (one-way). I means that:
- files which doesn't exist on remote side will be uploaded
- files will be updated if different than local copy
- files will be deleted if doesn't exist locally

We should assume that we are not modifying local copy - this is **one-way synchronisation**, this is why merge is not a right term here. There are different tactics of making synchronisation, possible scenarios:
- do not delete files on the server-side, even if don't exist locally
- only upload new files (do not update existing)

Any others?
