### ISSUE TITLE
Cheatsheet won't load correctly

### ISSUE THREAD

**Issue by adamwardecki** [Syncano/syncano-node#148]
1. Go to the docs main page (0 or master) https://master-docs.syncano.io/#/
2. Click on the Cheatsheet option from the resources tab

An empty screen will show up the url path is (https://master-cheatsheet.syncano.io/#/):
<img width="1439" alt="cheatsheet-load" src="https://user-images.githubusercontent.com/1017097/36252246-31805d88-1244-11e8-92e5-4f65f7d3804e.png">

The docs load after clicking on one of the tabs.

**Comment by mkucharz** [comment]
@adamwardecki is is still a case?

**Comment by adamwardecki** [comment]
It's working as expected now.
