### ISSUE TITLE
Socket templates not added when doing `npm i @syncano/cli@canary`

### ISSUE THREAD

**Issue by adamwardecki** [Syncano/syncano-node#172]
The templates are not present in the `node_modules/@syncano` folder and `npx s create <socket>` doesn't work for the canary version

<img width="1439" alt="npx_s_create_socket" src="https://user-images.githubusercontent.com/1017097/36670238-fa70f106-1af7-11e8-88ce-53d1dcfb5d65.png">

**Comment by mkucharz** [comment]
@adamwardecki I can't repeat that.. can you try once again?

**Comment by adamwardecki** [comment]
works with 0.12
