### ISSUE TITLE
"npx s search" doesn't return all the results 

### ISSUE THREAD

**Issue by adamwardecki** [Syncano/syncano-node#190]
Version: `@syncano/cli@0.9.3`
To reproduce:
`npx s search google` 

Returns nothing although we have `google-maps` and `google-geocoding` sockets available.

**Comment by mkucharz** [comment]
@adamwardecki make sure that, socket was publish using new CLI, on the main website we have still "old" registry we have to change it, but first we need to publish sockets using new CLI. New registry is here (https://registry-0.syncano.space) you can check that instance on Syncano Syncano account.

**Comment by adamwardecki** [comment]
Ok, I will get back to this once we republish sockets to the new registry.

**Comment by mkucharz** [comment]
I'm closing. We don't use our own registry anymore. Go to NPM ;)
