### ISSUE TITLE
Add support for .ts files in lib-js-test

### ISSUE THREAD

**Issue by Idered** [Syncano/syncano-node#215]
Right now it only supports `.js` files. https://github.com/Syncano/syncano-node/blob/55234bd384f6716be2bca48093863f2855598a1e/packages/lib-js-test/src/index.js#L108

![](https://i.imgur.com/kWXWPcY.png)

**Comment by mkucharz** [comment]
Now we are running tests over the JS files from `.dist` folder, so it will work with any type of files until they are converted to `.js` files.
