### ISSUE TITLE
Wrong order of information while using npx s init when you're not logged in

### ISSUE THREAD

**Issue by maciejkorsan** [Syncano/syncano-node#259]
![screenshot 2018-09-06 13 24 51](https://user-images.githubusercontent.com/655235/45154642-83f93600-b1d8-11e8-86c9-eecd75c7e7f3.png)
]

after logging in when using `npx s init` info `You're in! Enjoy! 👍` shows up below project template selection

**Comment by mkucharz** [comment]
Fixed.
