### ISSUE TITLE
Delete instance description should say 'Delete an Instance'

### ISSUE THREAD

**Issue by jakubkornafel** [Syncano/syncano-node#274]
**Environment**
 - OS: MacOS High Sierra
 - Syncano version:  0.13.0-alpha.951da2cd

**Describe the bug**
`delete instance` description says 'Create an Instance' 

**To Reproduce**
1. npx s instance

**Expected behavior**
`delete instance` description should say 'Delete an Instance'

**Screenshots**
![screen shot 2018-10-08 at 13 05 48](https://user-images.githubusercontent.com/16954261/46605846-215ac900-cafb-11e8-936b-c7ff0a6683a6.png)

**Comment by mkucharz** [comment]
Closed by #284.
