### ISSUE TITLE
npx s add is not working

### ISSUE THREAD

**Issue by maciejkorsan** [Syncano/syncano-node#322]
**Environment**
   cli version: 0.14.0 
  node version: v8.9.3 
   npm version: 6.4.1 
      platform: Darwin 
          arch: x64 
 
**Describe the bug**

```
npx s add calendar
 
Unhandled Rejection! TypeError: _commands2.default.SocketAdd is not a constructor

Please file an issue here:
https://github.com/Syncano/syncano-node/issues 
```

**Comment by mkucharz** [comment]
Hm. It is not supported anymore, we are using NPM as our registry. But it should be definitely removed from the list of commands.  What are you trying to do?

**Comment by maciejkorsan** [comment]
just playing around and wondering why it's still on the list ;) (I thought that this is the method which adds new socket to the project, and then I realized that we have *create* to do this job, but *add* is still on the list)
