### ISSUE TITLE
Beta syncano-cli init - error no such api key

### ISSUE THREAD

**Issue by maciejkorsan** [Syncano/syncano-node#52]
I've installed syncano-cli@beta and wanted to start a new project.

```
 syncano-cli init
 
    New project? Exciting! 🎉 
 
?   Choose template for your project     hello - Hello World template (recommend
ed)
 
    Creating Syncano Instance... No such API Key.

**Comment by adamwardecki** [comment]
@maciejkorsan  Looks like you are not logged in. Maybe your account has expired?

**Comment by maciejkorsan** [comment]
I had an old configuration (expired account) in ~/syncano.yml, I've removed it, logged in again and now it works

**Comment by adamwardecki** [comment]
Glad you made it work. Looks like the error message should be more verbose in this case.

**Comment by mkucharz** [comment]
@adamwardecki @maciejkorsan I think that in this case we should as for login and password.. what do you think?

**Comment by maciejkorsan** [comment]
yeah, ask for login or suggest to check/remove ~/syncano.yml

**Comment by maciejkorsan** [comment]
or do something like angular does when error is raised - provide link to docs

**Comment by mkucharz** [comment]
We can do something much more sophisticated, bo what do you think about something like this for now?

<img width="895" alt="screen shot 2017-12-19 at 17 47 30" src="https://user-images.githubusercontent.com/4037961/34168410-c0cdf168-e4e4-11e7-8bd0-1c421273a1cf.png">

**Comment by maciejkorsan** [comment]
@mkucharz good :)
