### ISSUE TITLE
Syncano-cli call throws error on grouped endpoint

### ISSUE THREAD

**Issue by Andela-callen** [Syncano/syncano-node#57]
`s call` throws error message on grouped endpoint (e.g `s call stripe/charge/createcharges/`) when run on command line, but, endpoint works fine in postman and browers.

In defining the grouped endpoint, the following steps were taken:
- Create a `charge folder` in `src folder`
- create charge related script file (e.g. `createCharges.js`, `retrieveCharges.js`, e.t.c.) in `src/charge folder`
- Define endpoint in socket.yml file as shown below (**N/B**: without the file path):
<img width="566" alt="screen shot 2017-12-08 at 7 16 10 pm" src="https://user-images.githubusercontent.com/24938072/33779224-50766a8a-dc4c-11e7-8721-37cbf82bee6e.png">

Error message:
> No such endpoint on the server! Make sure you have synced your socket.

**Comment by mkucharz** [comment]
@Andela-callen @adamwardecki I think actually that kind of format of the endpoint name can create lot more of such problems and for now should be forbidden. Fo example if `file` parameter is not specified Syncano will search for `src/<filename>.js`... with path separator in it that can be troublesome.

**Comment by 23doors** [comment]
Haven't tested it but checked the code and seems that it should look for `src/charge/createCharges.js` in this case and work correctly with path separators

**Comment by mkucharz** [comment]
@23doors do you think we should support it? It is a nice twist, but it is not gonna work with windows (not sure if we will ever try to bring support in non-linux env).

**Comment by 23doors** [comment]
@mkucharz hm. It should work on windows as well. Unless I misunderstood something. Backend should deal with it normally (as we're dealing with a zipfile anyway so path delimeter is always the same for us) and node also seem to always use '/' in `require` as path delimeter (at least I wasn't able to find any info about it being different). So it seems there is no harm in adding support for it in `s call` as well.

**Comment by mkucharz** [comment]
@23doors @Andela-callen ok, I'll try to support that feature then
