### ISSUE TITLE
[ URGENT ][ AGAIN ]  Syncano-core update method returns dict on reference

### ISSUE THREAD

**Issue by aexol** [Syncano/syncano-node#61]
@Idered 
```
{type: "reference", target: "article", value: 6988}
```

**Comment by Idered** [comment]
Expanding references and relations is not implemented for create and update methods.

**Comment by aexol** [comment]
Nooo its a bug not feature! it should return just
```
6988
```
Thats how its implemented in syncano-server
@Idered

**Comment by aexol** [comment]
It should never expand references as this would be too big cost for database.

**Comment by Idered** [comment]
@aexol can you please provide full query and version of syncano-server/syncano-core you use?

**Comment by aexol** [comment]
latest syncano-core
```
await data.mymodel.update({mydata})
```

**Comment by aexol** [comment]
@Idered

**Comment by Idered** [comment]
@aexol this should be resolved in latest @syncano/core@canary

**Comment by Idered** [comment]
@aexol does it work for you?

**Comment by aexol** [comment]
```
	"dummyowner": {
		"type": "reference",
		"target": "user",
		"value": 2
	},
```
nope

**Comment by aexol** [comment]
```
	"file": {
		"type": "file",
		"value": "https://d3rij3t703q5l6.cloudfront.net/31451/2/cb8166d4f0baf25b3ce03d4534c04bb1fe49281c.jpg"
	},
```

**Comment by aexol** [comment]
@Idered

**Comment by aexol** [comment]
update method

**Comment by aexol** [comment]
done
