### ISSUE TITLE
syncano hosting sync - error after filename change

### ISSUE THREAD

**Issue by maciejkorsan** [Syncano/syncano-node#63]
https://www.dropbox.com/s/pc18i8eg0rqq8c8/Screenshot%202017-12-21%2014.10.57.png?dl=0

can't sync files after renaming one before first sync

**Comment by maciejkorsan** [comment]
This is not a renaming issue - it's generated by spaces in the filename, try 'hello world.js'

**Comment by mkucharz** [comment]
@maciejkorsan @23doors will add support for urlencoded file names and then I'll add support in CLI

**Comment by mkucharz** [comment]
@23doors can you confirm that we have urlencoded support already?

**Comment by 23doors** [comment]
@mkucharz We do
